name: Rust

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo fmt -- --check
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - run: cargo test --verbose
